### PR TITLE
downgrade certinfo errors/warnings to debug (SOFTWARE-4980)

### PR DESCRIPTION
**Pull request by edquist**
@brianhlin per discussion this morning as a first step for SOFTWARE-4980 we want to eliminate the certinfo error and warning messages.

I wasn't sure if it would be best to remove them entirely, so I've just downgraded them to debug-level messages.

Let me know if you'd like to handle this differently.

### CODE REVIEW

**Comment by brianhlin** [comment]
When we're troubleshooting, we generally tell people to set the DebugLevel to 5, don't we? I'd rather not have these messages polluting our troubleshooting session so I'd rather remove them outright

**Comment by edquist** [comment]
Alright, i've updated the PR to comment these out instead.  Effectively they are removed, but i'm leaving in the comments to help make sense of the surrounding certinfo code for when we rip all that out too.

**Comment by brianhlin** [comment]
Fine by me. Could you add a comment explaining why we're commenting them out with a reference to the Jira ticket?

**Comment by edquist** [comment]
Sure thing; added.

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
