### PR TITLE
Fixup for SOFTWARE-4928 and add some logging on query failure

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by brianhlin** [comment]
Oops, something still looks off

**Comment by brianhlin** [comment]
I dropped in the file from my branch into the container and things seem appear to be chugging along!

**Comment by matyasselmeci** [comment]
What happens to an upgrade install if there's a database present with the old schema?

**Comment by brianhlin** [comment]
I imagine that it'd fail! But I moved the old db out of the way so it's running with the new schema so we don't have to worry about it this time around

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
